### ISSUE TITLE
Define desired functionalities of this project

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/COMET-cmd-gen#1]
I learned from @wcparker that an automated COMET csv generator would make our life easier. Still, we are unclear about the functionalities we needed, so @LegyPlegy @SummerLeaves please propose your ideas here.

**Comment by wcparker** [comment]
Thoughts so far:  We need separate csv's for each e-link (0-19).  It would be great if these could all be generated at once.  It would also be useful to be able to specify a short string of bytes and loop it to fill the csv.  Finally, if we could implement filling the csv with pseudorandom numbers that would also be helpful (we don't need this one right away).

**Comment by LegyPlegy** [comment]
~Moved this from rpi.burnin issue to here


The COMET boards currently require manual manipulation of ~20 CSV files which each contain 260 lines of 8 digit numbers where each represents a registry byte to be configured onto the COMET. These CSVs are fed directly into the 20 eLinks on the COMET board with one CSV per eLink. 

A useful tool to have would be a python-based script that could allow users to modify these CSVs and input their own configurations for these CSV files for debugging purposes testing DCBs.

### List of example features:
 - User-input patterns to be repeated in the list of 256 bytes, e.g all 1's, all 0's, repeating 01010101, alternate between the serial no and 00000000.
 - More control over separate CSV edits, e.g. edit CSVs 1-5 and 8-10, edit CSVs 1-20, edit CSV 5 only
 - 

### Extra Info
Each CSV has a "template" that needs to be consistent (Lines 1-3 are 'open' commands, lines 4-259 are the code, and line 260 is a 'close' command)

**Comment by SummerLeaves** [comment]
I made a simple CSV file generator last night, and Will has approved it for further development. I'll begin working on the opening preamble, random number generation, and other aspects of the program. (More details after he's available)

@yipengsun Having trouble uploading it to github.

**Comment by yipengsun** [comment]
@SummerLeaves Sorry for the late reply, but I do think you have permission to push to the `master` branch of this repository. Please try again. If it still doesn't work, let's work it out tomorrow.

**Comment by SummerLeaves** [comment]
@yipengsun  

No problem with the late reply - If we're talking about the uploading the CSV file generator to this branch, I pushed a working iteration of it to the master branch during the first week of school. I'm coming in tomorrow, but my file should be under this path:
COMET-cmd-gen/TestCSV_MultipleFileGeneration_V2.py

Thanks!
